impl TypeUrl for MsgTransfer
cosmos/cosmos-rust pull request #296
Opened 2022-10-05 08:55 UTC by Magicloud

2022-10-06 02:38 UTC, tony-iqlusion requested changes
PR looks good, but can you run rustfmt?

2022-10-06 02:38 UTC, tony-iqlusion commented on cosmos-sdk-proto/src/type_urls.rs
> +    const TYPE_URL: &'static str = "ibc.applications.transfer.v1.MsgTransfer";
Needs a leading slash:

```suggestion
    const TYPE_URL: &'static str = "/ibc.applications.transfer.v1.MsgTransfer";
```

2022-10-12 15:37 UTC, Magicloud commented on cosmos-sdk-proto/src/type_urls.rs
> +    const TYPE_URL: &'static str = "ibc.applications.transfer.v1.MsgTransfer";
Thanks.

2022-10-24 16:06 UTC, tony-iqlusion approved these changes

2022-10-24 16:07 UTC, merged